name: pana
version: 0.1.2-dev
description: Dart Package ANAlysis
author: Kevin Moore <github@j832.com>
homepage: https://github.com/kevmoo/pana.dart
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  http: ^0.11.3
  http_parser: ^1.0.0
  logging: ^0.11.0
  path: ^1.3.6
  stack_trace: ^1.4.2
executables:
  pana:
